default: &default
  adapter: postgresql
  encoding: utf8
  # schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= "#{ENV['POSTGRES_DB']}_test" %>


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: descriptor_production
  username: code-descriptor
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>

